repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: local
  hooks:
  - id: repomix-pack
    name: Pack codebase with repomix
    entry: uv run repomix
    args: [.]
    language: system
    pass_filenames: false
    always_run: true
