[project]
name = "hronir"
version = "0.1.0"
description = "The Hrönir Encyclopedia"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Hrönir Contributors"}]

# dependencies
dependencies = [
    "click",
    "pandas",
    "google-generativeai",
    "sqlalchemy>=2.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "black"
]

[project.scripts]
hronir = "hronir_encyclopedia.cli:main"
