import os

import google.generativeai as genai

from . import storage

# Environment variables are loaded from system environment

MODEL_NAME = "gemini-2.5-flash-preview-05-20"


def _gemini_request(prompt: str) -> str:
    """Return text generated by Gemini using the google-generativeai client."""
    key = os.getenv("GEMINI_API_KEY")
    if not key:
        raise RuntimeError("GEMINI_API_KEY not set")

    genai.configure(api_key=key)
    model = genai.GenerativeModel(MODEL_NAME)

    # Configure safety settings
    safety_settings = [
        {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
        {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
        {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
        {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
    ]

    response = model.generate_content(prompt, safety_settings=safety_settings)
    return response.text


def generate_chapter(prompt: str, prev_uuid: str | None = None) -> str:
    """Generate a chapter with Gemini and store it."""
    text = _gemini_request(prompt)
    return storage.store_chapter_text(text)
